export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const PASSWORD_FORGET = '/forgot'
export const HOME = '/#/home'
export const ACCOUNT = '/account'
export const NOT_ALLOWED = 'notAllowed'
